services:
  - type: web
    name: fullstack-user-auth
    env: node
    buildCommand: |
      cd client
      npm install
      npm run build
      cd ../server
      npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: YOUR_MONGODB_CONNECTION_STRING
    buildFilter:
      paths:
        - client/**
        - server/**
